### ISSUE TITLE
onStart KeyError

### ISSUE THREAD

**Issue by frontfoto** [flopp999/MEATERLink-Domoticz#1]
Tried to install the plugin, followed the instructions from github but when added to domoticz I find this in domoticz log. and MEATERCloud.log doesn't give any info.

> 2021-12-19 10:06:28.656 Error: Meater: 'onStart' failed 'KeyError':'('MEATERCloud',)'.
2021-12-19 10:06:28.656 Error: Meater: Exception traceback:
2021-12-19 10:06:28.656 Error: Meater: ----> Line 159 in '/home/zait/domoticz/plugins/MEATERLink-Domoticz/plugin.py'
2021-12-19 10:06:28.656 Error: Meater: ----> Line 77 in '/home/zait/domoticz/plugins/MEATERLink-Domoticz/plugin.py'

> 2021-12-19 10:06:38.072 Error: Meater: 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'GetToken''.
2021-12-19 10:06:38.072 Error: Meater: Exception traceback:
2021-12-19 10:06:38.072 Error: Meater: ----> Line 212 in '/home/zait/domoticz/plugins/MEATERLink-Domoticz/plugin.py'
2021-12-19 10:06:38.072 Error: Meater: ----> Line 151 in '/home/zait/domoticz/plugins/MEATERLink-Domoticz/plugin.py'

**Comment by flopp999** [comment]
Have you downloaded ZIP-files to same as plugin.py?

**Comment by frontfoto** [comment]
Haven't downloaded any files separated. The files are located in plugins, in a folder named MEATERLink-Domoticz as above. In the folder there is 2 zipfiles one png, Plugin.py

**Comment by frontfoto** [comment]
Every files comes from me using git clone as described on github

**Comment by flopp999** [comment]
In setup-custom icons do you see MEATERcloud?

**Comment by frontfoto** [comment]
<img width="375" alt="Screenshot 2021-12-19 at 11 27 30" src="https://user-images.githubusercontent.com/55498696/146671740-847b7f20-7e1b-4d62-a74a-0b8bd8e88a77.png">
Yes, that works.

**Comment by frontfoto** [comment]
The error above is when domoticz tries to start the plugin.

**Comment by frontfoto** [comment]
Tried to update Domoticz to latest beta. All other plugin runs fine only Meater not starting.

**Comment by flopp999** [comment]
I see the problem.
Give a minute to fix it

**Comment by flopp999** [comment]
please try

sudo git pull
then restart DZ

**Comment by frontfoto** [comment]
Plugin is up and running. Will report back if it generates some new errors.

**Comment by flopp999** [comment]
thanks for letting me now this problem
